import type { Metadata } from "next";
import { Poppins } from "next/font/google";  // Only import Poppins font
import "./globals.css";
import Footer from "@/components/footer";
// Initialize Poppins font
const poppins = Poppins({
  variable: "--font-poppins",  // Custom variable name for Poppins font
  subsets: ["latin"],  // You can also specify other subsets if needed
  weight: ["400", "700"],  // Specify the font weights you want to include
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}> {/* Apply Poppins font globally */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
